# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('avail_bikes', models.IntegerField()),
                ('all_stands', models.IntegerField()),
                ('free_stands', models.IntegerField()),
                ('coordinates', location_field.models.plain.PlainLocationField(max_length=63)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
