# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_stands', models.IntegerField()),
                ('coordinates', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_bikes', models.IntegerField()),
                ('free_stands', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Location')),
            ],
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
