# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_bikes', models.IntegerField()),
                ('free_stands', models.IntegerField()),
                ('time', models.TimeField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Location')),
            ],
        ),
    ]
