# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_means'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='means',
            name='avail_bikes',
        ),
        migrations.RemoveField(
            model_name='means',
            name='free_stands',
        ),
        migrations.RemoveField(
            model_name='means',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='means',
            name='avail_bikes_mean',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='means',
            name='avail_bikes_sd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='means',
            name='free_stands_mean',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='means',
            name='free_stands_sd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='means',
            name='month',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
