# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20180417_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_bikes_mean', models.FloatField()),
                ('free_stands_mean', models.FloatField()),
                ('avail_bikes_sd', models.FloatField()),
                ('free_stands_sd', models.FloatField()),
                ('time', models.TimeField()),
                ('timestamp', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='means',
            name='location',
        ),
        migrations.DeleteModel(
            name='Means',
        ),
    ]
