# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20180417_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='timestamp',
            new_name='month',
        ),
    ]
