# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20180417_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='avail_bikes_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='avail_bikes_sd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='free_stands_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='free_stands_sd',
            field=models.FloatField(null=True),
        ),
    ]
