# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20180418_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='weekend',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='weekend',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
